[package]
name = "nash-cli"
version = "0.2.1"
edition.workspace = true
description = "The Nash programming language"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "nash_cli"
path = "src/lib.rs"

[[bin]]
name = "nash"
path = "src/main.rs"

[dependencies]
clap.workspace = true
color-print.workspace = true
dirs.workspace = true
futures.workspace = true
miette.workspace = true
nash-config = { path = "../nash-config", version = "0.3.0" }
nash-driver = { path = "../nash-driver", version = "0.2.0" }
nash-language-server = { path = "../nash-language-server", version = "0.2.0" }
octocrab.workspace = true
tar.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "io-std"] }
tokio-util = { version = "0.7.18", features = ["compat"] }
tower-lsp-server.workspace = true
xz2.workspace = true
zip.workspace = true
