use std::{
    ffi::OsStr,
    fs,
    path::{Path, PathBuf},
    process::Command,
};

use proc_macro2::{Ident, Span, TokenStream};
use quote::quote;
use walkdir::WalkDir;

/// These tests currently fail because we do not support "counting mode" yet.
/// Once counting mode is implemented, these tests should not be skipped.
const SKIP_TESTS: &[&str] = &[
    "builtin_semantics_droplist_droplist_09",
    "builtin_semantics_droplist_droplist_10",
    "builtin_semantics_droplist_droplist_14",
    "builtin_semantics_droplist_droplist_15",
    "builtin_semantics_droplist_droplist_16",
];

fn rustfmt(path: &Path) {
    let status = Command::new("cargo")
        .args(["fmt", "--", path.to_str().unwrap()])
        .status()
        .expect("failed to run cargo fmt");

    assert!(status.success(), "cargo fmt failed");
}

fn main() {
    let conformance_dir: PathBuf = ["crates", "nash-plutus", "tests", "conformance"]
        .iter()
        .collect();

    let output_path: PathBuf = ["crates", "nash-plutus", "tests", "conformance.rs"]
        .iter()
        .collect();

    let mut tests: Vec<(String, PathBuf)> = Vec::new();

    for entry in WalkDir::new(&conformance_dir)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        let path = entry.path();

        if path.extension().and_then(OsStr::to_str) != Some("uplc") {
            continue;
        }

        let test_name = path
            .strip_prefix(&conformance_dir)
            .unwrap()
            .parent()
            .unwrap()
            .to_str()
            .unwrap()
            .replace(|c: char| !c.is_alphanumeric(), "_")
            .to_lowercase();

        if SKIP_TESTS.contains(&test_name.as_str()) {
            continue;
        }

        tests.push((test_name, path.to_path_buf()));
    }

    tests.sort_by(|a, b| a.0.cmp(&b.0));

    let test_fns: Vec<TokenStream> = tests
        .iter()
        .map(|(test_name, path)| {
            let rel_path = path
                .strip_prefix(Path::new("crates/nash-plutus/tests"))
                .unwrap();
            let rel_str = rel_path.to_str().unwrap();
            let expected = format!("{rel_str}.expected");
            let budget = format!("{rel_str}.budget.expected");
            let ident = Ident::new(test_name, Span::call_site());

            quote! {
                #[test]
                fn #ident() {
                    run_test(
                        include_str!(#rel_str),
                        include_str!(#expected),
                        include_str!(#budget),
                    );
                }
            }
        })
        .collect();

    let tokens = quote! {
        use nash_plutus::machine::PlutusVersion;

        fn run_test(file_contents: &str, expected_output: &str, expected_budget: &str) {
            let arena = nash_plutus::arena::Arena::new();

            let Ok(program) =
                nash_plutus::syn::parse_program(&arena, file_contents).into_result()
            else {
                pretty_assertions::assert_eq!("parse error", expected_output);
                pretty_assertions::assert_eq!("parse error", expected_budget);

                return;
            };

            let result = program.eval_version(&arena, PlutusVersion::V3);

            let info = result.info;

            let Ok(term) = result.term else {
                pretty_assertions::assert_eq!("evaluation failure", expected_output);
                pretty_assertions::assert_eq!("evaluation failure", expected_budget);

                return;
            };

            let expected = nash_plutus::syn::parse_program(&arena, expected_output)
                .into_result()
                .unwrap();

            pretty_assertions::assert_eq!(expected.term, term);

            let consumed_budget = format!(
                "({{cpu: {}\n| mem: {}}})",
                info.consumed_budget.cpu, info.consumed_budget.mem
            );

            pretty_assertions::assert_eq!(consumed_budget, expected_budget);
        }

        #(#test_fns)*
    };

    // Validate syntax
    let _: syn::File = syn::parse2(tokens.clone()).expect("generated code should be valid syntax");

    let code = format!(
        "// @generated by generate-conformance-tests\n// Do not edit manually.\n\n{tokens}"
    );

    fs::write(&output_path, code).unwrap();
    rustfmt(&output_path);

    println!(
        "Generated {} tests to {}",
        tests.len(),
        output_path.display()
    );
}
