[package]
name = "nash-config"
version = "0.2.0"
edition.workspace = true
description = "Nash project configuration file parsing"
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
jsonc-parser.workspace = true
pubgrub.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
