[package]
name = "nash-ast"
version = "0.1.0"
edition.workspace = true
description = "Canonical AST for the nash programming language"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
nash-region = { path = "../nash-region", version = "0.2.0" }
nash-source = { path = "../nash-source", version = "0.2.0" }
