[package]
name = "nash-can"
version.workspace = true
edition.workspace = true
description = "Canonicalize a nash source tree, resolving symbols, re-ordering definitions, and preparing a module for type inference."
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
