[package]
name = "nash-driver"
version = "0.2.1"
edition.workspace = true
description = "Build system and driver for Nash projects"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
bincode.workspace = true
bumpalo.workspace = true
glob.workspace = true
miette.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "fs"] }
url.workspace = true

nash-config = { path = "../nash-config", version = "0.3.0" }
nash-ast = { path = "../nash-ast", version = "0.3.1" }
nash-can = { path = "../nash-can", version = "0.3.1" }
nash-constrain = { path = "../nash-constrain", version = "0.2.1" }
nash-parse = { path = "../nash-parse", version = "0.2.2" }
nash-region = { path = "../nash-region", version = "0.2.0" }
nash-solve = { path = "../nash-solve", version = "0.2.1" }
nash-source = { path = "../nash-source", version = "0.3.0" }

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
