[package]
name = "nashc"
version = "0.1.0"
edition.workspace = true
description = "Compiler for the nash programming language"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "nashc"
path = "src/main.rs"

[dependencies]
miette.workspace = true
nash-driver.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
