[package]
name = "nash-solve"
version = "0.2.1"
edition.workspace = true
description = "The entry point of nash's type inference system. Implements type inference and specialization of traits."
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo.workspace = true
nash-ast = { path = "../nash-ast", version = "0.3.1" }
nash-can = { path = "../nash-can", version = "0.3.1" }
nash-constrain = { path = "../nash-constrain", version = "0.2.1" }
nash-region = { path = "../nash-region", version = "0.2.0" }

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
nash-parse = { path = "../nash-parse", version = "0.2.2" }
nash-source = { path = "../nash-source", version = "0.3.0" }
