[package]
name = "nash-parse"
version = "0.2.0"
edition.workspace = true
description = "Parser for the nash programming language"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo.workspace = true
nash-region = { path = "../nash-region", version = "0.2.0" }
nash-source = { path = "../nash-source", version = "0.2.0" }

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
