[package]
name = "nash-parse"
version.workspace = true
edition.workspace = true
description = "Parser for the nash programming language"
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo.workspace = true
nash-region.workspace = true
nash-source.workspace = true

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
